### ISSUE TITLE
Log when app-engine.xml do not exists

### ISSUE THREAD

**Issue by dnascimento** [AppScale/appscale-tools#398]
If the app-engine.xml does not exists, the following stacktrace happens. The error message at interface is just: "coercing to Unicode: need string or buffer, NoneType found". 
Take a look in appengine_helper.py:233 to add a better info message :) It happens if the app-engine.xml is not found.

```
stacktrace : Traceback (most recent call last):
  File "/usr/local/appscale-tools/bin/appscale", line 87, in <module>
    appscale.deploy(sys.argv[2])
  File "/usr/local/appscale-tools/bin/../lib/appscale.py", line 449, in deploy
    return AppScaleTools.upload_app(options)
  File "/usr/local/appscale-tools/bin/../lib/appscale_tools.py", line 561, in upload_app
    app_id = AppEngineHelper.get_app_id_from_app_config(file_location)
  File "/usr/local/appscale-tools/bin/../lib/appengine_helper.py", line 165, in get_app_id_from_app_config
    app_config_file = cls.get_config_file_from_dir(app_dir)
  File "/usr/local/appscale-tools/bin/../lib/appengine_helper.py", line 233, in get_config_file_from_dir
    elif os.path.exists(cls.get_appengine_web_xml_location(app_dir)):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

exception : TypeError

locale : en_US

tools_version : 1.14.0

platform : Linux-3.2.0-32-generic-x86_64-with-Ubuntu-12.04-precise

message : coercing to Unicode: need string or buffer, NoneType found

runtime : CPython
```

**Comment by cdonati** [comment]
This was fixed with #686
