### ISSUE TITLE
Build error: rsa requires Python '>=3.5, <4' but the running Python is 2.7.17

### ISSUE THREAD

**Issue by kerbymart** [AppScale/appscale-tools#773]
The guide is outdated: https://github.com/AppScale/appscale-tools/wiki/Installing-the-AppScale-Tools-on-Linux

To prevent the error "rsa requires Python '>=3.5, <4' but the running Python is 2.7.17", run the following command:
```
pip install google-api-python-client==1.5.4 oauth2client==4.0.0 rsa==4.0
```

**Comment by kerbymart** [comment]
And then running `appscale init cluster` throws:

```
$ appscale init cluster
Traceback (most recent call last):
  File "/usr/local/bin/appscale", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'azure-core>=1.24.0' distribution was not found and is required by msrest
```
